- hosts: kernel_settings
  connection: local
  gather_facts: false
  tasks:
    - name: Update workflow files
      include_tasks: tasks/create_pr.yml
      vars:
        __branch_name: workflow_files
        __pr_title: Update workflow files
        __pr_body: Update workflow files
        __create_pr_files: "{{
          dict(workflow_dest | zip(workflow_src)) |
          combine(files_to_delete) }}"
        workflow_src: "{{ workflow_files | map('regex_replace', '^(.+)$', playbook_dir ~ '/files/\\1') }}"
        workflow_dest: "{{ workflow_files | map('regex_replace', '^(.+)$', '.github/\\1') }}"
        files_to_delete:
          .github/workflows/tox.yml: DELETE

- hosts: kernel_settings
  connection: local
  gather_facts: false
  tasks:
    - name: Update python workflow files
      include_tasks: tasks/create_pr.yml
      vars:
        __branch_name: python_workflow_files
        __pr_title: Update python workflow files
        __pr_body: Update python workflow files
        __create_pr_files: "{{
          dict(workflow_dest | zip(workflow_src)) }}"
        workflow_src: "{{ python_workflow_files | map('regex_replace', '^(.+)$', playbook_dir ~ '/files/\\1') }}"
        workflow_dest: "{{ python_workflow_files | map('regex_replace', '^(.+)$', '.github/\\1') }}"

    - name: Enable CodeQL
      debug:
        msg: Enabling CodeQL
      when: enable_codeql | d(false)
